#pragma once
#include <stdint.h>

// Block IDs

enum BlockID : uint16_t {
  BLOCK_AIR = 0,
  BLOCK_STONE = 1,
  BLOCK_GRASS = 2,
  BLOCK_DIRT = 3,
  BLOCK_COBBLESTONE = 4,
  BLOCK_WOOD_PLANK = 5,
  BLOCK_SAPLING = 6,
  BLOCK_TALLGRASS = 31,
  BLOCK_BEDROCK = 7,
  BLOCK_WATER_FLOW = 8,
  BLOCK_WATER_STILL = 9,
  BLOCK_LAVA_FLOW = 10,
  BLOCK_LAVA_STILL = 11,
  BLOCK_SAND = 12,
  BLOCK_GRAVEL = 13,
  BLOCK_GOLD_ORE = 14,
  BLOCK_IRON_ORE = 15,
  BLOCK_COAL_ORE = 16,
  BLOCK_LOG = 17,
  BLOCK_LEAVES = 18,
  BLOCK_GLASS = 20,
  BLOCK_LAPIS_ORE = 21,
  BLOCK_SANDSTONE = 24,
  BLOCK_WOOL = 35,
  BLOCK_FLOWER = 37,
  BLOCK_ROSE = 38,
  BLOCK_MUSHROOM_BROWN = 39,
  BLOCK_MUSHROOM_RED = 40,
  BLOCK_GOLD_BLOCK = 41,
  BLOCK_IRON_BLOCK = 42,
  BLOCK_STONE_SLAB = 44,
  BLOCK_BRICK = 45,
  BLOCK_TNT = 46,
  BLOCK_BOOKSHELF = 47,
  BLOCK_MOSSY_COBBLE = 48,
  BLOCK_OBSIDIAN = 49,
  BLOCK_TORCH = 50,
  BLOCK_FIRE = 51,
  BLOCK_CHEST = 54,
  BLOCK_DIAMOND_ORE = 56,
  BLOCK_DIAMOND_BLOCK = 57,
  BLOCK_CRAFTING_TABLE = 58,
  BLOCK_CROPS = 59,
  BLOCK_FARMLAND = 60,
  BLOCK_FURNACE = 61,
  BLOCK_SIGN = 63,
  BLOCK_DOOR_WOOD = 64,
  BLOCK_LADDER = 65,
  BLOCK_RAIL = 66,
  BLOCK_COBBLE_STAIR = 67,
  BLOCK_LEVER = 69,
  BLOCK_STONE_PLATE = 70,
  BLOCK_DOOR_IRON = 71,
  BLOCK_WOOD_PLATE = 72,
  BLOCK_REDSTONE_ORE = 73,
  BLOCK_TORCH_REDSTONE = 75,
  BLOCK_SNOW = 78,
  BLOCK_ICE = 79,
  BLOCK_SNOW_BLOCK = 80,
  BLOCK_CACTUS = 81,
  BLOCK_CLAY = 82,
  BLOCK_REEDS = 83,
  BLOCK_PUMPKIN = 86,
  BLOCK_NETHERRACK = 87,
  BLOCK_SOULSAND = 88,
  BLOCK_GLOWSTONE = 89,
  BLOCK_EMERALD_ORE = 129,
  BLOCK_STONE_BRICKS = 98,
  BLOCK_FENCE = 85,
  BLOCK_WOOD_STAIR = 53,

  // Custom IDs for colored wool variants (metadata-less representation).
  BLOCK_WOOL_ORANGE = 200,
  BLOCK_WOOL_MAGENTA = 201,
  BLOCK_WOOL_LIGHT_BLUE = 202,
  BLOCK_WOOL_YELLOW = 203,
  BLOCK_WOOL_LIME = 204,
  BLOCK_WOOL_PINK = 205,
  BLOCK_WOOL_GRAY = 206,
  BLOCK_WOOL_LIGHT_GRAY = 207,
  BLOCK_WOOL_CYAN = 208,
  BLOCK_WOOL_PURPLE = 209,
  BLOCK_WOOL_BLUE = 210,
  BLOCK_WOOL_BROWN = 211,
  BLOCK_WOOL_GREEN = 212,
  BLOCK_WOOL_RED = 213,
  BLOCK_WOOL_BLACK = 214,
  BLOCK_WOOD_SLAB = 215,
  BLOCK_COBBLE_SLAB = 216,
  BLOCK_SANDSTONE_SLAB = 217,
  BLOCK_BRICK_SLAB = 218,
  BLOCK_STONE_BRICK_SLAB = 219,
  BLOCK_STONE_SLAB_TOP = 220,
  BLOCK_WOOD_SLAB_TOP = 221,
  BLOCK_COBBLE_SLAB_TOP = 222,
  BLOCK_SANDSTONE_SLAB_TOP = 223,
  BLOCK_BRICK_SLAB_TOP = 224,
  BLOCK_STONE_BRICK_SLAB_TOP = 225,
  BLOCK_STONE_STAIR = 108,
  BLOCK_BRICK_STAIR = 109,
  BLOCK_SANDSTONE_STAIR = 128,
  BLOCK_STONE_BRICK_STAIR = 130,
  BLOCK_WOOD_STAIR_EAST = 226,
  BLOCK_WOOD_STAIR_SOUTH = 227,
  BLOCK_WOOD_STAIR_WEST = 228,
  BLOCK_COBBLE_STAIR_EAST = 229,
  BLOCK_COBBLE_STAIR_SOUTH = 230,
  BLOCK_COBBLE_STAIR_WEST = 231,
  BLOCK_STONE_STAIR_EAST = 232,
  BLOCK_STONE_STAIR_SOUTH = 233,
  BLOCK_STONE_STAIR_WEST = 234,
  BLOCK_SANDSTONE_STAIR_EAST = 235,
  BLOCK_SANDSTONE_STAIR_SOUTH = 236,
  BLOCK_SANDSTONE_STAIR_WEST = 237,
  BLOCK_BRICK_STAIR_EAST = 238,
  BLOCK_BRICK_STAIR_SOUTH = 239,
  BLOCK_BRICK_STAIR_WEST = 240,
  BLOCK_STONE_BRICK_STAIR_EAST = 241,
  BLOCK_STONE_BRICK_STAIR_SOUTH = 242,
  BLOCK_STONE_BRICK_STAIR_WEST = 243,
  BLOCK_WOOD_STAIR_TOP = 150,
  BLOCK_WOOD_STAIR_TOP_EAST = 151,
  BLOCK_WOOD_STAIR_TOP_SOUTH = 152,
  BLOCK_WOOD_STAIR_TOP_WEST = 153,
  BLOCK_COBBLE_STAIR_TOP = 154,
  BLOCK_COBBLE_STAIR_TOP_EAST = 155,
  BLOCK_COBBLE_STAIR_TOP_SOUTH = 156,
  BLOCK_COBBLE_STAIR_TOP_WEST = 157,
  BLOCK_STONE_STAIR_TOP = 158,
  BLOCK_STONE_STAIR_TOP_EAST = 159,
  BLOCK_STONE_STAIR_TOP_SOUTH = 160,
  BLOCK_STONE_STAIR_TOP_WEST = 161,
  BLOCK_SANDSTONE_STAIR_TOP = 162,
  BLOCK_SANDSTONE_STAIR_TOP_EAST = 163,
  BLOCK_SANDSTONE_STAIR_TOP_SOUTH = 164,
  BLOCK_SANDSTONE_STAIR_TOP_WEST = 165,
  BLOCK_BRICK_STAIR_TOP = 166,
  BLOCK_BRICK_STAIR_TOP_EAST = 167,
  BLOCK_BRICK_STAIR_TOP_SOUTH = 168,
  BLOCK_BRICK_STAIR_TOP_WEST = 169,
  BLOCK_STONE_BRICK_STAIR_TOP = 170,
  BLOCK_STONE_BRICK_STAIR_TOP_EAST = 171,
  BLOCK_STONE_BRICK_STAIR_TOP_SOUTH = 172,
  BLOCK_STONE_BRICK_STAIR_TOP_WEST = 173,

  BLOCK_COUNT = 256
};

// Block properties
struct BlockProps {
  uint8_t hardness_x10; // hardness * 10 (0 = indestructible)
  uint8_t light_emit;   // emitted light [0..15]
  uint8_t light_block;  // blocked light [0..15]
  uint8_t flags;        // bit 0: solid, bit 1: transparent, bit 2: liquid

  // Bounding box for block highlight (0.0 to 1.0)
  float minX, minY, minZ;
  float maxX, maxY, maxZ;

  bool isSolid() const { return (flags & 1) != 0; }
  bool isTransparent() const { return (flags & 2) != 0; }
  bool isLiquid() const { return (flags & 4) != 0; }
  bool isOpaque() const { return isSolid() && !isTransparent(); }
};

extern BlockProps g_blockProps[BLOCK_COUNT];

// Texture coordinate mappings
struct BlockUV {
  uint8_t top_x, top_y;   // top face
  uint8_t side_x, side_y; // side faces
  uint8_t bot_x, bot_y;   // bottom face
};

extern BlockUV g_blockUV[BLOCK_COUNT];

// Initialize tables - called at startup
void Blocks_Init();

static inline bool isBaseStairId(uint8_t id) {
  return id == BLOCK_STONE_STAIR || id == BLOCK_WOOD_STAIR || id == BLOCK_COBBLE_STAIR ||
         id == BLOCK_SANDSTONE_STAIR || id == BLOCK_BRICK_STAIR || id == BLOCK_STONE_BRICK_STAIR;
}

static inline bool isStairId(uint8_t id) {
  return isBaseStairId(id) ||
         (id >= BLOCK_WOOD_STAIR_EAST && id <= BLOCK_STONE_BRICK_STAIR_WEST) ||
         (id >= BLOCK_WOOD_STAIR_TOP && id <= BLOCK_STONE_BRICK_STAIR_TOP_WEST);
}

static inline uint8_t stairBaseId(uint8_t id) {
  switch (id) {
    case BLOCK_WOOD_STAIR:
    case BLOCK_WOOD_STAIR_EAST:
    case BLOCK_WOOD_STAIR_SOUTH:
    case BLOCK_WOOD_STAIR_WEST: return BLOCK_WOOD_STAIR;
    case BLOCK_WOOD_STAIR_TOP:
    case BLOCK_WOOD_STAIR_TOP_EAST:
    case BLOCK_WOOD_STAIR_TOP_SOUTH:
    case BLOCK_WOOD_STAIR_TOP_WEST: return BLOCK_WOOD_STAIR;
    case BLOCK_COBBLE_STAIR:
    case BLOCK_COBBLE_STAIR_EAST:
    case BLOCK_COBBLE_STAIR_SOUTH:
    case BLOCK_COBBLE_STAIR_WEST: return BLOCK_COBBLE_STAIR;
    case BLOCK_COBBLE_STAIR_TOP:
    case BLOCK_COBBLE_STAIR_TOP_EAST:
    case BLOCK_COBBLE_STAIR_TOP_SOUTH:
    case BLOCK_COBBLE_STAIR_TOP_WEST: return BLOCK_COBBLE_STAIR;
    case BLOCK_STONE_STAIR:
    case BLOCK_STONE_STAIR_EAST:
    case BLOCK_STONE_STAIR_SOUTH:
    case BLOCK_STONE_STAIR_WEST: return BLOCK_STONE_STAIR;
    case BLOCK_STONE_STAIR_TOP:
    case BLOCK_STONE_STAIR_TOP_EAST:
    case BLOCK_STONE_STAIR_TOP_SOUTH:
    case BLOCK_STONE_STAIR_TOP_WEST: return BLOCK_STONE_STAIR;
    case BLOCK_SANDSTONE_STAIR:
    case BLOCK_SANDSTONE_STAIR_EAST:
    case BLOCK_SANDSTONE_STAIR_SOUTH:
    case BLOCK_SANDSTONE_STAIR_WEST: return BLOCK_SANDSTONE_STAIR;
    case BLOCK_SANDSTONE_STAIR_TOP:
    case BLOCK_SANDSTONE_STAIR_TOP_EAST:
    case BLOCK_SANDSTONE_STAIR_TOP_SOUTH:
    case BLOCK_SANDSTONE_STAIR_TOP_WEST: return BLOCK_SANDSTONE_STAIR;
    case BLOCK_BRICK_STAIR:
    case BLOCK_BRICK_STAIR_EAST:
    case BLOCK_BRICK_STAIR_SOUTH:
    case BLOCK_BRICK_STAIR_WEST: return BLOCK_BRICK_STAIR;
    case BLOCK_BRICK_STAIR_TOP:
    case BLOCK_BRICK_STAIR_TOP_EAST:
    case BLOCK_BRICK_STAIR_TOP_SOUTH:
    case BLOCK_BRICK_STAIR_TOP_WEST: return BLOCK_BRICK_STAIR;
    case BLOCK_STONE_BRICK_STAIR:
    case BLOCK_STONE_BRICK_STAIR_EAST:
    case BLOCK_STONE_BRICK_STAIR_SOUTH:
    case BLOCK_STONE_BRICK_STAIR_WEST: return BLOCK_STONE_BRICK_STAIR;
    case BLOCK_STONE_BRICK_STAIR_TOP:
    case BLOCK_STONE_BRICK_STAIR_TOP_EAST:
    case BLOCK_STONE_BRICK_STAIR_TOP_SOUTH:
    case BLOCK_STONE_BRICK_STAIR_TOP_WEST: return BLOCK_STONE_BRICK_STAIR;
    default: return id;
  }
}

// 0=north, 1=east, 2=south, 3=west
static inline int stairFacing(uint8_t id) {
  switch (id) {
    case BLOCK_WOOD_STAIR_EAST:
    case BLOCK_COBBLE_STAIR_EAST:
    case BLOCK_STONE_STAIR_EAST:
    case BLOCK_SANDSTONE_STAIR_EAST:
    case BLOCK_BRICK_STAIR_EAST:
    case BLOCK_STONE_BRICK_STAIR_EAST: return 1;
    case BLOCK_WOOD_STAIR_TOP_EAST:
    case BLOCK_COBBLE_STAIR_TOP_EAST:
    case BLOCK_STONE_STAIR_TOP_EAST:
    case BLOCK_SANDSTONE_STAIR_TOP_EAST:
    case BLOCK_BRICK_STAIR_TOP_EAST:
    case BLOCK_STONE_BRICK_STAIR_TOP_EAST: return 1;
    case BLOCK_WOOD_STAIR_SOUTH:
    case BLOCK_COBBLE_STAIR_SOUTH:
    case BLOCK_STONE_STAIR_SOUTH:
    case BLOCK_SANDSTONE_STAIR_SOUTH:
    case BLOCK_BRICK_STAIR_SOUTH:
    case BLOCK_STONE_BRICK_STAIR_SOUTH: return 2;
    case BLOCK_WOOD_STAIR_TOP_SOUTH:
    case BLOCK_COBBLE_STAIR_TOP_SOUTH:
    case BLOCK_STONE_STAIR_TOP_SOUTH:
    case BLOCK_SANDSTONE_STAIR_TOP_SOUTH:
    case BLOCK_BRICK_STAIR_TOP_SOUTH:
    case BLOCK_STONE_BRICK_STAIR_TOP_SOUTH: return 2;
    case BLOCK_WOOD_STAIR_WEST:
    case BLOCK_COBBLE_STAIR_WEST:
    case BLOCK_STONE_STAIR_WEST:
    case BLOCK_SANDSTONE_STAIR_WEST:
    case BLOCK_BRICK_STAIR_WEST:
    case BLOCK_STONE_BRICK_STAIR_WEST: return 3;
    case BLOCK_WOOD_STAIR_TOP_WEST:
    case BLOCK_COBBLE_STAIR_TOP_WEST:
    case BLOCK_STONE_STAIR_TOP_WEST:
    case BLOCK_SANDSTONE_STAIR_TOP_WEST:
    case BLOCK_BRICK_STAIR_TOP_WEST:
    case BLOCK_STONE_BRICK_STAIR_TOP_WEST: return 3;
    default: return 0;
  }
}

static inline bool isUpsideDownStair(uint8_t id) {
  switch (id) {
    case BLOCK_WOOD_STAIR_TOP:
    case BLOCK_WOOD_STAIR_TOP_EAST:
    case BLOCK_WOOD_STAIR_TOP_SOUTH:
    case BLOCK_WOOD_STAIR_TOP_WEST:
    case BLOCK_COBBLE_STAIR_TOP:
    case BLOCK_COBBLE_STAIR_TOP_EAST:
    case BLOCK_COBBLE_STAIR_TOP_SOUTH:
    case BLOCK_COBBLE_STAIR_TOP_WEST:
    case BLOCK_STONE_STAIR_TOP:
    case BLOCK_STONE_STAIR_TOP_EAST:
    case BLOCK_STONE_STAIR_TOP_SOUTH:
    case BLOCK_STONE_STAIR_TOP_WEST:
    case BLOCK_SANDSTONE_STAIR_TOP:
    case BLOCK_SANDSTONE_STAIR_TOP_EAST:
    case BLOCK_SANDSTONE_STAIR_TOP_SOUTH:
    case BLOCK_SANDSTONE_STAIR_TOP_WEST:
    case BLOCK_BRICK_STAIR_TOP:
    case BLOCK_BRICK_STAIR_TOP_EAST:
    case BLOCK_BRICK_STAIR_TOP_SOUTH:
    case BLOCK_BRICK_STAIR_TOP_WEST:
    case BLOCK_STONE_BRICK_STAIR_TOP:
    case BLOCK_STONE_BRICK_STAIR_TOP_EAST:
    case BLOCK_STONE_BRICK_STAIR_TOP_SOUTH:
    case BLOCK_STONE_BRICK_STAIR_TOP_WEST:
      return true;
    default:
      return false;
  }
}

static inline uint8_t toOrientedStairId(uint8_t baseId, int facing, bool upsideDown = false) {
  int f = facing & 3;
  if (!upsideDown && f == 0) return stairBaseId(baseId);
  switch (stairBaseId(baseId)) {
    case BLOCK_WOOD_STAIR:
      if (upsideDown) return (f == 0) ? BLOCK_WOOD_STAIR_TOP : (f == 1) ? BLOCK_WOOD_STAIR_TOP_EAST : (f == 2) ? BLOCK_WOOD_STAIR_TOP_SOUTH : BLOCK_WOOD_STAIR_TOP_WEST;
      return (f == 1) ? BLOCK_WOOD_STAIR_EAST : (f == 2) ? BLOCK_WOOD_STAIR_SOUTH : BLOCK_WOOD_STAIR_WEST;
    case BLOCK_COBBLE_STAIR:
      if (upsideDown) return (f == 0) ? BLOCK_COBBLE_STAIR_TOP : (f == 1) ? BLOCK_COBBLE_STAIR_TOP_EAST : (f == 2) ? BLOCK_COBBLE_STAIR_TOP_SOUTH : BLOCK_COBBLE_STAIR_TOP_WEST;
      return (f == 1) ? BLOCK_COBBLE_STAIR_EAST : (f == 2) ? BLOCK_COBBLE_STAIR_SOUTH : BLOCK_COBBLE_STAIR_WEST;
    case BLOCK_STONE_STAIR:
      if (upsideDown) return (f == 0) ? BLOCK_STONE_STAIR_TOP : (f == 1) ? BLOCK_STONE_STAIR_TOP_EAST : (f == 2) ? BLOCK_STONE_STAIR_TOP_SOUTH : BLOCK_STONE_STAIR_TOP_WEST;
      return (f == 1) ? BLOCK_STONE_STAIR_EAST : (f == 2) ? BLOCK_STONE_STAIR_SOUTH : BLOCK_STONE_STAIR_WEST;
    case BLOCK_SANDSTONE_STAIR:
      if (upsideDown) return (f == 0) ? BLOCK_SANDSTONE_STAIR_TOP : (f == 1) ? BLOCK_SANDSTONE_STAIR_TOP_EAST : (f == 2) ? BLOCK_SANDSTONE_STAIR_TOP_SOUTH : BLOCK_SANDSTONE_STAIR_TOP_WEST;
      return (f == 1) ? BLOCK_SANDSTONE_STAIR_EAST : (f == 2) ? BLOCK_SANDSTONE_STAIR_SOUTH : BLOCK_SANDSTONE_STAIR_WEST;
    case BLOCK_BRICK_STAIR:
      if (upsideDown) return (f == 0) ? BLOCK_BRICK_STAIR_TOP : (f == 1) ? BLOCK_BRICK_STAIR_TOP_EAST : (f == 2) ? BLOCK_BRICK_STAIR_TOP_SOUTH : BLOCK_BRICK_STAIR_TOP_WEST;
      return (f == 1) ? BLOCK_BRICK_STAIR_EAST : (f == 2) ? BLOCK_BRICK_STAIR_SOUTH : BLOCK_BRICK_STAIR_WEST;
    case BLOCK_STONE_BRICK_STAIR:
      if (upsideDown) return (f == 0) ? BLOCK_STONE_BRICK_STAIR_TOP : (f == 1) ? BLOCK_STONE_BRICK_STAIR_TOP_EAST : (f == 2) ? BLOCK_STONE_BRICK_STAIR_TOP_SOUTH : BLOCK_STONE_BRICK_STAIR_TOP_WEST;
      return (f == 1) ? BLOCK_STONE_BRICK_STAIR_EAST : (f == 2) ? BLOCK_STONE_BRICK_STAIR_SOUTH : BLOCK_STONE_BRICK_STAIR_WEST;
    default: return baseId;
  }
}
